## 使用tushare 获取股票数据

In [1]:
# https://tushare.pro/document/2?doc_id=95
!pip install tushare

Looking in indexes: http://pypi.douban.com/simple
Collecting tushare
  Downloading http://pypi.doubanio.com/packages/bf/3f/149ef2a80cddd24410e6788228a22f3b3afb5c55c765a223a5c7ecf93ecf/tushare-1.2.48-py3-none-any.whl (211kB)
Installing collected packages: tushare
Successfully installed tushare-1.2.48

- date：日期
- open：开盘价
- high：最高价
- close：收盘价
- low：最低价
- volume：成交量
- price_change：价格变动
- p_change：涨跌幅
- ma5：5日均价
- ma10：10日均价
- ma20:20日均价
- v_ma5:5日均量
- v_ma10:10日均量
- v_ma20:20日均量
- turnover:换手率[注：指数无此项]

In [1]:
import tushare as ts
# 获取 上证50ETF 510050 （上证大蓝筹）
# 获取 沪深300ETF 510300 (沪深大蓝筹)
# 获取 创业板ETF 159952 （创业板整体行情）
data_50 = ts.get_hist_data('510050', start='2010-01-01', end='2020-01-01')
data_300 = ts.get_hist_data('510300', start='2010-01-01', end='2020-01-01')
data_cy = ts.get_hist_data('159952', start='2010-01-01', end='2020-01-01')

column_dict = {'date':'日期','open':'开盘价','high':'最高价','close':'收盘价','low':'最低价','volume':'成交量',\
'price_change':'价格变动','p_change':'涨跌幅','ma5':'5日均价','ma10':'10日均价','ma20':'20日均价','v_ma5':'5日均量',\
'v_ma10':'10日均量','v_ma20':'20日均量','turnover':'换手率'}

data_50.rename(columns=column_dict, inplace=True)
data_300.rename(columns=column_dict, inplace=True)
data_cy.rename(columns=column_dict, inplace=True)
data_50

,开盘价,最高价,收盘价,最低价,成交量,价格变动,涨跌幅,5日均价,10日均价,20日均价,5日均量,10日均量,20日均量
date,,,,,,,,,,,,,
2019-12-31,3.05,3.06,3.06,3.04,4343767.00,0.01,0.33,3.020,3.011,2.982,5253076.20,4876928.15,4621398.78
2019-12-30,3.01,3.06,3.05,3.00,5714000.50,0.04,1.33,3.006,3.008,2.975,5103696.00,5136142.80,4540381.10
2019-12-27,3.01,3.04,3.01,3.00,6153844.00,0.01,0.33,2.992,3.002,2.967,5068166.10,5304241.15,4397897.31
2019-12-26,2.98,3.01,3.00,2.98,5075314.50,0.02,0.67,2.992,3.001,2.964,4782160.30,5315085.70,4468831.01
2019-12-25,2.98,2.99,2.98,2.97,4978455.00,-0.01,-0.33,2.994,2.995,2.963,4525747.60,5154952.43,4386112.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-07-14,2.64,2.67,2.67,2.63,2483724.50,0.03,1.14,2.618,2.618,2.618,3032204.90,3032204.90,3032204.90
2017-07-13,2.60,2.64,2.64,2.60,3178567.00,0.04,1.54,2.605,2.605,2.605,3169325.00,3169325.00,3169325.00
2017-07-12,2.60,2.64,2.60,2.59,3300303.25,0.00,0.00,2.593,2.593,2.593,3166244.33,3166244.33,3166244.33
2017-07-11,2.57,2.63,2.60,2.57,3741320.75,0.02,0.78,2.590,2.590,2.590,3099214.88,3099214.88,3099214.88
2017-07-10,2.56,2.58,2.58,2.55,2457109.00,0.02,0.78,2.580,2.580,2.580,2457109.00,2457109.00,2457109.00

In [29]:
data_300

,开盘价,最高价,收盘价,最低价,成交量,价格变动,涨跌幅,5日均价,10日均价,20日均价,5日均量,10日均量,20日均量
date,,,,,,,,,,,,,
2019-12-31,4.07,4.10,4.10,4.06,3521859.00,0.02,0.49,4.042,4.023,3.987,3948429.45,3690241.08,3136446.41
2019-12-30,4.01,4.09,4.08,4.00,5423814.50,0.06,1.49,4.020,4.017,3.978,3869641.85,3863685.63,3059629.41
2019-12-27,4.03,4.07,4.02,4.02,4368130.00,0.00,0.00,3.996,4.007,3.969,3679168.45,3624152.48,2875616.54
2019-12-26,3.99,4.03,4.02,3.99,3322559.50,0.03,0.75,3.996,4.002,3.962,3463102.10,3623422.43,2808668.59
2019-12-25,3.99,4.00,3.99,3.97,3105784.25,0.00,0.00,3.996,3.989,3.958,3326974.20,3428318.38,2727281.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-07-14,3.73,3.76,3.76,3.72,855766.50,0.03,0.80,3.714,3.714,3.714,1081604.91,1081604.91,1081604.91
2017-07-13,3.69,3.73,3.73,3.69,1112379.38,0.04,1.08,3.703,3.703,3.703,1138064.52,1138064.52,1138064.52
2017-07-12,3.71,3.73,3.69,3.68,1174760.75,-0.02,-0.54,3.693,3.693,3.693,1146626.23,1146626.23,1146626.23
2017-07-11,3.68,3.74,3.71,3.68,1314196.88,0.03,0.81,3.695,3.695,3.695,1132558.97,1132558.97,1132558.97
2017-07-10,3.68,3.70,3.68,3.68,950921.06,0.00,0.00,3.680,3.680,3.680,950921.06,950921.06,950921.06

In [30]:
data_cy

,开盘价,最高价,收盘价,最低价,成交量,价格变动,涨跌幅,5日均价,10日均价,20日均价,5日均量,10日均量,20日均量
date,,,,,,,,,,,,,
2019-12-31,1.03,1.04,1.04,1.03,222130.16,0.00,0.00,1.034,1.032,1.019,245458.71,266447.48,290562.96
2019-12-30,1.02,1.04,1.04,1.01,249825.16,0.02,1.96,1.032,1.032,1.015,274750.90,295897.75,298331.45
2019-12-27,1.04,1.05,1.02,1.02,317426.19,-0.02,-1.92,1.026,1.031,1.012,299762.67,298363.66,300278.14
2019-12-26,1.03,1.04,1.04,1.03,210078.02,0.01,0.97,1.028,1.031,1.009,283508.44,300300.76,302601.43
2019-12-25,1.03,1.03,1.03,1.02,227834.02,0.00,0.00,1.028,1.027,1.005,286339.65,300773.08,301984.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-07-14,0.99,1.00,0.98,0.97,161009.27,-0.01,-1.01,0.996,0.996,0.996,93904.56,93904.56,93904.56
2017-07-13,1.00,1.00,0.99,0.99,55668.31,-0.01,-1.00,1.000,1.000,1.000,77128.38,77128.38,77128.38
2017-07-12,1.00,1.00,1.00,0.99,72199.18,0.00,0.00,1.003,1.003,1.003,84281.74,84281.74,84281.74
2017-07-11,1.00,1.01,1.00,1.00,74687.05,-0.01,-0.99,1.005,1.005,1.005,90323.02,90323.02,90323.02
2017-07-10,1.02,1.02,1.01,1.01,105958.99,-0.01,-0.98,1.010,1.010,1.010,105958.99,105958.99,105958.99

In [36]:
# 格力电器
data_000651 = ts.get_hist_data('000651', start='2010-01-01', end='2020-01-01')
data_000651.tail()

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20
date,,,,,,,,,,,,,
2017-07-14,40.82,41.33,41.08,40.40,441473.31,0.07,0.17,40.694,40.694,40.694,779376.59,779376.59,779376.59
2017-07-13,40.77,41.38,41.01,40.46,507538.31,0.22,0.54,40.598,40.598,40.598,863852.41,863852.41,863852.41
2017-07-12,41.53,41.75,40.79,40.43,860734.50,-0.74,-1.78,40.460,40.460,40.460,982623.77,982623.77,982623.77
2017-07-11,39.30,41.65,41.53,39.18,1428060.62,2.47,6.32,40.295,40.295,40.295,1043568.41,1043568.41,1043568.41
2017-07-10,38.50,39.37,39.06,38.46,659076.19,0.65,1.69,39.060,39.060,39.060,659076.19,659076.19,659076.19

In [40]:
pro = ts.pro_api('5df81af6960855783739669d20a081e4a567ace885caa939e65c182d')
df = pro.daily(ts_code='000651.SZ', start_date='20100101', end_date='20200101')
df

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,000651.SZ,20191231,65.35,65.86,64.80,65.58,65.58,0.00,0.0000,209307.99,1.366603e+06
1,000651.SZ,20191230,64.57,65.70,64.05,65.58,64.53,1.05,1.6272,264579.81,1.724507e+06
2,000651.SZ,20191227,65.15,65.76,64.40,64.53,64.78,-0.25,-0.3859,249793.35,1.624183e+06
3,000651.SZ,20191226,64.46,64.80,64.25,64.78,64.40,0.38,0.5901,165339.53,1.066133e+06
4,000651.SZ,20191225,65.00,65.19,64.15,64.40,65.02,-0.62,-0.9536,198372.40,1.283338e+06
...,...,...,...,...,...,...,...,...,...,...,...
2258,000651.SZ,20100108,25.58,26.19,25.31,26.19,25.60,0.59,2.3000,201098.79,5.191319e+05
2259,000651.SZ,20100107,26.77,26.84,25.30,25.60,26.75,-1.15,-4.3000,465363.30,1.198048e+06
2260,000651.SZ,20100106,27.42,27.64,26.51,26.75,27.34,-0.59,-2.1600,300022.06,8.059785e+05
2261,000651.SZ,20100105,28.20,28.43,27.25,27.34,28.16,-0.82,-2.9100,168777.11,4.658009e+05
2262,000651.SZ,20100104,29.00,29.10,28.15,28.16,28.94,-0.78,-2.7000,90970.74,2.593518e+05

In [43]:
df = pro.daily(ts_code='510050', start_date='20100101', end_date='20200101')
df

Empty DataFrame
Columns: [ts_code, trade_date, open, high, low, close, pre_close, change, pct_chg, vol, amount]
Index: []

|名称|类型|默认显示|描述|
|----|----|----|----|
|ts_code|str|Y|TS代码|
|trade_date|str|Y|交易日期|
|open|float|Y|开盘价(元)|
|high|float|Y|最高价(元)|
|low|float|Y|最低价(元)|
|close|float|Y|收盘价(元)|
|pre_close|float|Y|昨收盘价(元)|
|change|float|Y|涨跌额(元)|
|pct_chg|float|Y|涨跌幅(%)|
|vol|float|Y|成交量(手)|
|amount|float|Y|成交额(千元)|

In [11]:
column_dict = {'ts_code':'TS代码', 'trade_date':'交易日期', 'open':'开盘价(元)',\
               'high':'最高价(元)', 'low':'最低价(元)', 'close':'收盘价(元)', \
               'pre_close':'昨收盘价(元)', 'change':'涨跌额(元)', \
               'pct_chg':'涨跌幅(%)', 'vol':'成交量(手)', 'amount':'成交额(千元)'}

pro = ts.pro_api('cc563f482cce240deb38a7711e95f274e4fe11ae8b07c697dd3ded89')
etf_50_df_1 = pro.fund_daily(ts_code='510050.SH', start_date='20100101', end_date='20130101')
etf_50_df_1.rename(columns=column_dict, inplace=True)
etf_50_df_1
pd.to_csv('data/etf50_1.csv', )

,TS代码,交易日期,昨收盘价(元),开盘价(元),最高价(元),最低价(元),收盘价(元),涨跌额(元),涨跌幅(%),成交量(手),成交额(千元)
0,510050.SH,20121231,1.814,1.819,1.855,1.819,1.854,0.040,2.2051,3663139.07,674232.226
1,510050.SH,20121228,1.786,1.785,1.817,1.784,1.814,0.028,1.5677,3613363.61,651120.804
2,510050.SH,20121227,1.799,1.809,1.814,1.785,1.786,-0.013,-0.7226,3549448.37,636937.685
3,510050.SH,20121226,1.793,1.793,1.804,1.791,1.799,0.006,0.3346,3010511.93,541134.731
4,510050.SH,20121225,1.747,1.738,1.807,1.734,1.793,0.046,2.6331,5890460.46,1048865.376
...,...,...,...,...,...,...,...,...,...,...,...
724,510050.SH,20100108,2.462,2.458,2.468,2.427,2.462,0.000,0.0000,8854760.13,2168222.331
725,510050.SH,20100107,2.512,2.513,2.526,2.449,2.462,-0.050,-1.9904,8942675.14,2226035.249
726,510050.SH,20100106,2.544,2.539,2.550,2.511,2.512,-0.032,-1.2579,5465724.97,1384265.012
727,510050.SH,20100105,2.512,2.525,2.562,2.489,2.544,0.032,1.2739,10998787.55,2781187.358
728,510050.SH,20100104,2.559,2.569,2.572,2.510,2.512,-0.047,-1.8367,7864332.06,2000121.183

In [12]:
etf_50_df_2 = pro.fund_daily(ts_code='510050.SH', start_date='20130101', end_date='20160101')
etf_50_df_2.rename(columns=column_dict, inplace=True)
etf_50_df_2

,TS代码,交易日期,昨收盘价(元),开盘价(元),最高价(元),最低价(元),收盘价(元),涨跌额(元),涨跌幅(%),成交量(手),成交额(千元)
0,510050.SH,20151231,2.424,2.418,2.434,2.405,2.416,-0.008,-0.3300,3458720.70,837061.955
1,510050.SH,20151230,2.432,2.433,2.434,2.395,2.424,-0.008,-0.3289,2753570.90,664689.596
2,510050.SH,20151229,2.412,2.411,2.434,2.406,2.432,0.020,0.8292,2969462.84,718736.233
3,510050.SH,20151228,2.486,2.487,2.495,2.408,2.412,-0.074,-2.9767,2740406.18,670217.662
4,510050.SH,20151225,2.478,2.480,2.493,2.470,2.486,0.008,0.3228,1735857.89,430786.858
...,...,...,...,...,...,...,...,...,...,...,...
722,510050.SH,20130110,1.848,1.848,1.871,1.839,1.849,0.001,0.0541,2668491.42,495040.885
723,510050.SH,20130109,1.853,1.848,1.858,1.835,1.848,-0.005,-0.2698,2636745.07,487235.973
724,510050.SH,20130108,1.876,1.875,1.878,1.843,1.853,-0.023,-1.2260,3261195.91,605281.775
725,510050.SH,20130107,1.867,1.858,1.886,1.853,1.876,0.009,0.4821,3167598.72,593124.603
726,510050.SH,20130104,1.854,1.880,1.896,1.847,1.867,0.013,0.7012,5793368.89,1083892.117

In [14]:
etf_50_df_3 = pro.fund_daily(ts_code='510050.SH', start_date='20160101', end_date='20200101')
etf_50_df_3.rename(columns=column_dict, inplace=True)
etf_50_df_3

,TS代码,交易日期,昨收盘价(元),开盘价(元),最高价(元),最低价(元),收盘价(元),涨跌额(元),涨跌幅(%),成交量(手),成交额(千元)
0,510050.SH,20191231,3.051,3.046,3.060,3.038,3.058,0.007,0.2294,4343767.11,1324084.863
1,510050.SH,20191230,3.009,3.005,3.058,2.999,3.051,0.042,1.3958,5714000.64,1733531.710
2,510050.SH,20191227,3.002,3.005,3.040,3.002,3.009,0.007,0.2332,6153843.98,1860126.203
3,510050.SH,20191226,2.980,2.980,3.005,2.979,3.002,0.022,0.7383,5075314.62,1518286.393
4,510050.SH,20191225,2.988,2.984,2.985,2.967,2.980,-0.008,-0.2677,4978454.98,1482332.609
...,...,...,...,...,...,...,...,...,...,...,...
970,510050.SH,20160108,2.177,2.236,2.259,2.156,2.219,0.042,1.9293,5766769.37,1279000.234
971,510050.SH,20160107,2.317,2.286,2.286,2.165,2.177,-0.140,-6.0423,891669.22,199851.686
972,510050.SH,20160106,2.286,2.290,2.320,2.275,2.317,0.031,1.3561,4009534.04,921398.473
973,510050.SH,20160105,2.278,2.260,2.311,2.230,2.286,0.008,0.3512,6456995.81,1473642.292
974,510050.SH,20160104,2.416,2.411,2.413,2.271,2.278,-0.138,-5.7119,2985469.54,703760.451

In [15]:
etf_50_df_4 = pro.fund_daily(ts_code='510050.SH', start_date='20200101', end_date='20210101')
etf_50_df_4.rename(columns=column_dict, inplace=True)
etf_50_df_4

,TS代码,交易日期,昨收盘价(元),开盘价(元),最高价(元),最低价(元),收盘价(元),涨跌额(元),涨跌幅(%),成交量(手),成交额(千元)
0,510050.SH,20200108,3.062,3.050,3.053,3.024,3.033,-0.029,-0.9471,4421800.42,1343852.756
1,510050.SH,20200107,3.050,3.056,3.074,3.051,3.062,0.012,0.3934,3964978.44,1213624.513
2,510050.SH,20200106,3.068,3.053,3.082,3.029,3.050,-0.018,-0.5867,5843985.94,1788059.233
3,510050.SH,20200103,3.081,3.088,3.090,3.064,3.068,-0.013,-0.4219,3359493.92,1033552.694
4,510050.SH,20200102,3.058,3.071,3.100,3.070,3.081,0.023,0.7521,5154329.97,1589411.885

In [30]:
etf_50_df_1.to_csv('data/etf50_1.csv', index=False, encoding='GBK')
etf_50_df_2.to_csv('data/etf50_2.csv', index=False, encoding='GBK')
etf_50_df_3.to_csv('data/etf50_3.csv', index=False, encoding='GBK')
etf_50_df_4.to_csv('data/etf50_4.csv', index=False, encoding='GBK')